pan_controller:
  controller:
    package: dynamixel_controllers
    module: joint_position_controller
    type: JointPositionController
  joint_name: pan_joint
  joint_speed: 0.3
  motor:
    id: 1
    init: 3072
    min: 454
    max: 3867

tilt_controller:
  controller:
    package: dynamixel_controllers
    module: joint_position_controller
    type: JointPositionController
  joint_name: tilt_joint
  joint_speed: 0.3
  motor:
    id: 2
    init: 2048
    min: 1705
    max: 2729
